use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;

// Our program's own ID and ID_CONST (generated by declare_id! in lib.rs).
// The derive_mxe_pda!, derive_comp_def_pda!, and derive_sign_pda! macros
// use these to derive PDAs that include our program's key in the seeds.
// Our program's own IDs (from declare_id!) — needed by derive_mxe_pda! etc.
use crate::{ArciumSignerAccount, ID, ID_CONST};

use crate::constants::COMP_DEF_OFFSET_DNA_MATCH;
use crate::error::ErrorCode;
use crate::types::*;

// ─────────────────────────────────────────────────────────────────────────────
// RegisterUser
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Accounts)]
pub struct RegisterUser<'info> {
    #[account(mut)]
    pub owner: Signer<'info>,

    #[account(
        init,
        payer = owner,
        space = UserProfile::SIZE,
        seeds = [b"user_profile", owner.key().as_ref()],
        bump,
    )]
    pub user_profile: Account<'info, UserProfile>,

    pub system_program: Program<'info, System>,
}

// ─────────────────────────────────────────────────────────────────────────────
// UpdateDna
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Accounts)]
pub struct UpdateDna<'info> {
    #[account(mut)]
    pub owner: Signer<'info>,

    #[account(
        mut,
        seeds = [b"user_profile", owner.key().as_ref()],
        bump = user_profile.bump,
        has_one = owner,
    )]
    pub user_profile: Account<'info, UserProfile>,
}

// ─────────────────────────────────────────────────────────────────────────────
// InitDnaCompDef
// ─────────────────────────────────────────────────────────────────────────────

#[init_computation_definition_accounts("dna_match_v2", payer)]
#[derive(Accounts)]
pub struct InitDnaCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        mut,
        address = derive_mxe_pda!()
    )]
    pub mxe_account: Box<Account<'info, MXEAccount>>,

    #[account(mut)]
    /// CHECK: initialised by the Arcium program CPI.
    pub comp_def_account: UncheckedAccount<'info>,

    #[account(
        mut,
        address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot)
    )]
    /// CHECK: validated by the Arcium program.
    pub address_lookup_table: UncheckedAccount<'info>,

    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: Address Lookup Table program.
    pub lut_program: UncheckedAccount<'info>,

    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

// ─────────────────────────────────────────────────────────────────────────────
// RequestMatch
// ─────────────────────────────────────────────────────────────────────────────

#[queue_computation_accounts("dna_match_v2", requester)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct RequestMatch<'info> {
    #[account(mut)]
    pub requester: Signer<'info>,

    pub user_profile_a: Box<Account<'info, UserProfile>>,
    pub user_profile_b: Box<Account<'info, UserProfile>>,

    /// Singleton result PDA per (user_a, user_b) pair.
    #[account(
        init_if_needed,
        payer = requester,
        space = MatchResult::SIZE,
        seeds = [
            b"match_result",
            user_profile_a.owner.as_ref(),
            user_profile_b.owner.as_ref(),
        ],
        bump,
    )]
    pub match_result: Account<'info, MatchResult>,

    // ── Arcium accounts (injected by #[queue_computation_accounts]) ──────────

    #[account(
        init_if_needed,
        space = 9,
        payer = requester,
        seeds = [&SIGN_PDA_SEED],
        bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,

    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Box<Account<'info, MXEAccount>>,

    #[account(
        mut,
        address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: validated by the Arcium program.
    pub mempool_account: UncheckedAccount<'info>,

    #[account(
        mut,
        address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: validated by the Arcium program.
    pub executing_pool: UncheckedAccount<'info>,

    #[account(
        mut,
        address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: validated by the Arcium program.
    pub computation_account: UncheckedAccount<'info>,

    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_DNA_MATCH))]
    pub comp_def_account: Box<Account<'info, ComputationDefinitionAccount>>,

    #[account(
        mut,
        address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    pub cluster_account: Box<Account<'info, Cluster>>,

    #[account(mut, address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS)]
    pub pool_account: Account<'info, FeePool>,

    #[account(mut, address = ARCIUM_CLOCK_ACCOUNT_ADDRESS)]
    pub clock_account: Account<'info, ClockAccount>,

    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

// ─────────────────────────────────────────────────────────────────────────────
// DnaMatchV1Callback
//
// Called by the Arcium TEE after the circuit completes.
// #[callback_accounts] injects validation that the call originates from Arcium.
// match_result is passed as remaining_accounts[0] (writable) from request_match.
// ─────────────────────────────────────────────────────────────────────────────

#[callback_accounts("dna_match_v2")]
#[derive(Accounts)]
pub struct DnaMatchV2Callback<'info> {
    pub arcium_program: Program<'info, Arcium>,

    #[account(address = derive_comp_def_pda!(COMP_DEF_OFFSET_DNA_MATCH))]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,

    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,

    /// CHECK: validated by the Arcium program.
    pub computation_account: UncheckedAccount<'info>,

    #[account(address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet))]
    pub cluster_account: Account<'info, Cluster>,

    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: validated by address constraint.
    pub instructions_sysvar: AccountInfo<'info>,
}
